- name: Test Ansible Vault Password
  hosts: all
  gather_facts: no

  tasks:
    - name: Attempt to read Vault file
      include_vars:
        file: test_vault.yml
        name: vault_data
      register: vault_test
      ignore_errors: yes

    - name: Check if Vault file was read successfully
      fail:
        msg: "Vault password is incorrect"
      when: vault_test is failed

    - name: Vault password is correct
      debug:
        msg: "Vault password is correct and file was read successfully"
      when: vault_test is succeeded
