---
- hosts: oracle_hosts
  vars:
    bitbucket_base_url: "https://api.bitbucket.org/2.0/repositories/YOUR_ORG/YOUR_REPO/src/master/oracle/scripts"
    tns_entry: "MYDB"  # The name of your TNS entry

  tasks:
  - name: Retrieve Oracle SQL script from Bitbucket
    uri:
      url: "{{ bitbucket_base_url }}/{{ script_name }}"
      method: GET
      headers:
        Authorization: "Bearer YOUR_ACCESS_TOKEN"
      return_content: yes
    register: sql_script_content

  - name: Extract Oracle details from tns.names file
    shell: "cat /path/to/tns.names | grep -A 7 '{{ tns_entry }} ='"
    register: tns_details

  # Extract connection details, assuming a specific format; adjust as needed.
  - set_fact:
      oracle_hostname: "{{ tns_details.stdout | regex_search('HOST = ([^)]+)', '\\1') }}"
      oracle_port: "{{ tns_details.stdout | regex_search('PORT = ([^)]+)', '\\1') }}"
      oracle_service_name: "{{ tns_details.stdout | regex_search('SERVICE_NAME = ([^)]+)', '\\1') }}"
      oracle_username: "{{ tns_details.stdout | regex_search('USER = ([^)]+)', '\\1') }}"
      oracle_password: "{{ tns_details.stdout | regex_search('PASSWORD = ([^)]+)', '\\1') }}"

  - name: Execute the SQL script on Oracle database
    oracle_sql:
      username: "{{ oracle_username }}"
      password: "{{ oracle_password }}"
      hostname: "{{ oracle_hostname }}"
      port: "{{ oracle_port }}"
      service_name: "{{ oracle_service_name }}"
      sql: "{{ sql_script_content.content }}"
